#ifndef _EVENT_HELPER_H
#define _EVENT_HELPER_H

enum SIM_STATE { PARAMETER_SOURCE_CHOICE, PARAMETER_SET_VALUES, SIM_CALCULATE, SIM_VISUALIZE};
enum BUTTON_ACTION { PARAM_MAX_LAT_DOWN, PARAM_MAX_LAT_UP, PARAM_MAX_LONG_DOWN, PARAM_MAX_LONG_UP, PARAM_TRIP_WEIGHT_UP, PARAM_TRIP_WEIGHT_DOWN,
	PARAM_TIME_UP, PARAM_TIME_DOWN, PARAM_FLEET_SIZE_UP, PARAM_FLEET_SIZE_DOWN, PARAM_REQUEST_COUNT_UP, PARAM_REQUEST_COUNT_DOWN, PARAM_VENUE_COUNT_UP, PARAM_VENUE_COUNT_DOWN,
	PARAMETER_SOURCE_CHOOSE_CUSTOM, PARAMTER_CHOOSE_SOURCE_FILES};

#endif